#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        systemctl --system stop samo-radio.service >/dev/null 2>&1 || true
        systemctl --system disable samo-radio.service >/dev/null 2>&1 || true
        ;;
esac

exit 0
